include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.generated.dart'
    - '**.config.dart'
    - '**.gr.dart'
    - '**.g.dart'
    - 'lib/generated/*'
    - 'lib/firebase_options.dart'
    - 'pubspec.yaml'

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
