name: mapping
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-366.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  dartz: ^0.10.1
  auto_route: ^7.4.0
  cloud_firestore: ^4.8.2
  json_annotation: ^4.8.1
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  freezed: ^2.3.5
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.3
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true

