// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2O921dJyhTwxMnWk3vMjME8k7sUjs5Y',
    appId: '1:791599398715:android:deb75bc9cb53d9e11d811e',
    messagingSenderId: '791599398715',
    projectId: 'mapping-bc664',
    storageBucket: 'mapping-bc664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyF4yo5M3KYrAZP27akbFT0RvY1Q3pqe4',
    appId: '1:791599398715:ios:39af98df9ed11f531d811e',
    messagingSenderId: '791599398715',
    projectId: 'mapping-bc664',
    storageBucket: 'mapping-bc664.appspot.com',
    iosClientId: '791599398715-kc7biii7dkmk82l829k6fu889lncpbri.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapping',
  );
}
